# Generated by Django 4.2.1 on 2023-05-31 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumArt',
        ),
    ]
