# Generated by Django 4.2.1 on 2023-05-31 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_band_remove_song_preview_song_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
    ]
