# Generated by Django 4.2.1 on 2023-05-31 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_album_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': 'albums'},
        ),
    ]
